// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Ee52BNtdEnxCuIIRElokxpym9_bQr4o',
    appId: '1:118065038551:web:0ff89c269b424965a09c92',
    messagingSenderId: '118065038551',
    projectId: 'walleta-3eb79',
    authDomain: 'walleta-3eb79.firebaseapp.com',
    storageBucket: 'walleta-3eb79.firebasestorage.app',
    measurementId: 'G-EVFX2L3PE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ59b7ErAFoj1kgenoCiVuK7l3OmPkgis',
    appId: '1:118065038551:android:a0b7b85a823afa45a09c92',
    messagingSenderId: '118065038551',
    projectId: 'walleta-3eb79',
    storageBucket: 'walleta-3eb79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB15bHA4WGltC9n7Bpu_dYEhTja_k-Mihc',
    appId: '1:118065038551:ios:42d7b5603da63ec4a09c92',
    messagingSenderId: '118065038551',
    projectId: 'walleta-3eb79',
    storageBucket: 'walleta-3eb79.firebasestorage.app',
    androidClientId: '118065038551-shgr0c7b9npoupkghkdckacv20fl9ots.apps.googleusercontent.com',
    iosClientId: '118065038551-rlqg9unasm9qth8ktpp859s9ar27vj6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.walleta',
  );
}
